# Generated by Django 4.2 on 2023-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblogmodel',
            name='img_content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
