# Generated by Django 4.2 on 2023-06-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_privateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateUser',
        ),
    ]
